models/weekly.py
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from models import Base
from datetime import datetime
from tools.utils import generate_uuid
from flask import g, current_app


# 周报表
class Weekly(Base):
    __tablename__ = 'Week_Note'

    id = Column(String(32), default=generate_uuid, primary_key=True, nullable=False)
    title = Column(String(50), nullable=False)
    content = Column(String, nullable=False)
    replys = Column(Integer, nullable=False, default=0)
    views = Column(Integer, nullable=False, default=0)
    ct = Column(DateTime, default=datetime.utcnow)
    mt = Column(DateTime, nullable=False, default=datetime.utcnow)
    user_id = Column(String(32), ForeignKey('User.id'))
    type_id = Column(Integer, ForeignKey('Types.id'))
    
    def __init__(self, form, user_id):
        # 这里一定要 ** 去除字符串 **，否则jquery赋值html会出错
        self.title = form.get('title', '').replace("\r\n",'')
        self.content = form.get('content', '').replace("\r\n",'')
        self.type_id = form.get('type_id', '-1')
        self.mt = self.ct
        self.user_id = user_id
        
    def __repr__(self):
        return "<Note(id='{}', title='{}', content='{}', ct='{}')>".format(
            self.id, self.title, self.content, self.ct
        )
    
    def incre_views(self):
        self.views += 1
        g.my_session.commit()

    def incre_replys(self):
        self.replys += 1
        g.my_session.commit()

routes/weekly.py
from flask import (
    Blueprint,
    render_template,
    session,
    request,
    redirect,
    url_for,
    g,
    jsonify,
    flash,
    make_response,
    current_app,
)
from models.weekly import Weekly
from models.users import User
from models.conmments import Comments
from models.web_view import Web_View
from models.types import Types
from models.menus import Menus
from tools.utils import current_user_id, is_login
from tools.log import logger
import os, datetime


main = Blueprint('weekly', __name__)


@main.route('/new', methods=['GET'])
@is_login
def new():
    # 返回话题列表
    logger.info('新建文件')
    # TODO；需要优化
    topic = g.my_session.query(Types).all()
    return render_template('weekly/new.html', board=topic)


@main.route('/add', methods=['POST'])
@is_login
def add():
    form = request.form
    user_id = current_user_id()
    note = Weekly(form, user_id=user_id)
    Weekly.new(note)
    flash('发表文章成功', 'success')
    logger.info('add new note id<{}> title<{}>'.format(note.id, note.title))
    return redirect(url_for('index.index'))


@main.route('/detail/<id>/')
def detail(id):
    Web_View.incre_views()
    note = Weekly.find_by_id(id)
    if note is not None:
        note.incre_views()
    else:
        logger.error('get_obj_by_id is None')
  
    # 根据用户Id，查找作者
    author = User.find_by_id(note.user_id).user_name
    
    # 根据文章id，查找其所有评论
    comments = Comments.get_obj_by_filter(note_id=id)
    return render_template('weekly/detail.html', note=note, comments=comments, author=author)


@main.route('/delete/<id>')
@is_login
def delete(id):
    note = Weekly.find_by_id(id)
    title = note.title
    logger.info('note {} delete success'.format(title))
    Weekly.delete(note)
    return redirect(url_for('index.index'))
    

@main.route('/edit/<id>', methods=['GET', 'POST'])
@is_login
def edit(id):
    old_note = Weekly.find_by_id(id)
    content = request.form.get('content', '')
    # 如果为空字符串，表示还没有提交更改
    if content is '':
        topic = Types.get_obj_by_filter()
        author = User.find_by_id(old_note.user_id).user_name
        comments = Comments.get_obj_by_filter(note_id=id)
        return render_template('weekly/edit.html', note=old_note, comments=comments, author=author, board=topic)
    else:
        # 更新数据库
        new_note = Weekly(request.form, old_note.user_id)
        Weekly.update(old_note, new_note)
        return redirect(url_for('weekly.detail', id=id))


@main.route('/detail/add_commit/<id>', methods=['POST'])
@is_login
def add_comment(id):
    content = request.form.get('content', 'null')
    
    # 文章的评论数加1
    note = Weekly.find_by_id(id)
    if note is not None:
        note.incre_replys()
    
    obj = Comments(content, current_user_id(), id)
    Comments.new(obj)
    logger.info('note<{}> add comment '.format(id))
    return redirect(url_for('weekly.detail', id=id))


# 接收editormd中ajax发送的图片，保存到本地，并返回链接
@main.route('/img', methods=['POST'])
def upload_img():
    print('img here')
    file = request.files.get('editormd-image-file')
    if not file:
        res = {
            'success': 0,
            'message': u'图片为空或格式错误'
        }
        return jsonify(res)
    else:
        ex = os.path.splitext(file.filename)[1]
        filename = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file.save(os.path.join(current_app.config['IMG_PATH'], filename))
        logger.info('save img {}'.format(filename))
        res = {
            'success' : 1,
            'message' : u'success',
            'url' : url_for('weekly.get_img', filename=filename)
        }
        return jsonify(res)


# 返回图片
@main.route('/image/<filename>', methods=['GET', 'POST'])
def get_img(filename):
    with open(os.path.join(current_app.config['IMG_PATH'], filename), 'rb') as file:
        r = make_response(file.read())
        return r
        

templates/weekly/detail.html
{% extends 'base.html' %}
{% block title %} {{ note.title }} {% endblock %}


{% block center %}
<div class="entry-box">
    <div class="detail">
        <div class="detail-header">
            <h3>{{ note.title }}</h3>
        </div>
        <div class="detail-bottom">
            <p>
                发表时间 {{ note.ct }} •  作者 {{ author }} • 浏览 {{ note.views }}次 / 回复 {{ note.replys }}
                {% if session['user_name'] == author %}
                <div class="text-right">
                    <a class="btn btn-info" href={{ url_for('weekly.edit', id=note.id) }} >编辑</a>
                    <a class="btn btn-danger" href={{ url_for('weekly.delete', id=note.id) }} >删除</a>
                </div>
                {% endif %}
            </p>
        </div>
        <div class="detail-content">
            {{ note.content | safe }}
        </div>
    </div>
    <div class="reply">
        <div class="add-reply">
            <form role="form" class="form-horizontal" method="post" action=" {{ url_for('weekly.add_comment', id=note.id) }}">
                <div class="form-group">
                    <div class="col-md-6">
                        <textarea class="form-control" id="comment-content" rows="3" name="content"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
			            <button type="submit" id="submit-comment" class="btn btn-default">提交评论</button>
                        <!--<input type="button" value="提交评论" id="submit-comment"></input>-->
                    </div>
		        </div>
            </form>
        </div>
        <div class="reply-num" id="tmp">
            <h4> 评论 {{ note.replys }} </h4>
        </div>
        {% for c in comments %}
        <div class="reply-content">
            <div class="topic-author-avater">
                <!--头像-->
            </div>
            <div class="note-content"">
                <span> {{ c.content }} </span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock center %}

templates/weekly/edit.html
{% extends 'base.html' %}
{% block title %} 编辑文章 {% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/plugins/codesample/plugin.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/start_tinymce.js') }}"></script>
    <script>
        $(document).ready(function(){
            $("#note-title").val("{{ note.title | safe }}")
            // 此处bug不知如何解决
            $("#note-content").text("{{ note.content | safe }}")
        });
    </script>
{% endblock %}

{% block center %}
<div class="entry-box">
    <form class="form-horizontal" role="form" id="new-note" action="{{ url_for('weekly.edit', id=note.id) }}" method="post">
        <div class="form-group">
            <label for="title" class="col-lg-1 control-label">标题</label>
            <div class="col-lg-11">
                <input type="text" id="note-title" class="form-control" name='title' placeholder="输入标题">
                </input>
            </div>
        </div>
        <div class="form-group">
            <label for="board" class="col-lg-1 control-label" >版块</label>
            <div class="col-lg-11">
                <select class="form-control" id="type_id" name="type_id" required>
                    <option value="">请选择</option>
                    {% for b in board %}
                        <option value="{{ b.id }}">{{ b.title }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="board" class="col-lg-1 control-label" >正文</label>
            <div class="col-lg-11">
                <textarea  id="note-content" name="content"></textarea>
            </div>
        </div>
        <div class="form-group" >
             <div class="col-lg-offset-2 col-lg-2">
                 <button type="submit" class="btn btn-success">发表</button>
             </div>
        </div>
    </form>
</div>
{% endblock center %}

templates/weekly/new.html
{% extends 'base.html' %}
{% block title %} 发表文章 {% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/plugins/codesample/plugin.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/start_tinymce.js') }}"></script>
{% endblock %}

{% block center %}
    <div class="entry-box">
        <form class="form-horizontal" role="form" id="new-note" action="{{ url_for('.add') }}" method="post">
        <div class="form-group">
            <label for="title" class="control-label col-lg-1">标题</label>
            <div class="col-lg-11">
                <input type="text" class="form-control" name='title' placeholder="请输入标题"></input>
            </div>
        </div>
        <div class="form-group">
            <label for="board" class="col-lg-1 control-label" >版块</label>
            <div class="col-lg-11">
                <select class="form-control" name="type_id" required>
                    <option value="">请选择</option>
                    {% for b in board %}
                        <option value="{{ b.id }}">{{ b.title }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="board" class="col-lg-1 control-label" >正文</label>
            <div class="col-lg-11">
                <textarea id="content" name="content"></textarea>
            </div>
        </div>
        <div class="form-group" >
             <div class="center-block">
                 <center><button type="submit" class="btn btn-success">发表</button></center>
             </div>
        </div>
    </form>
    </div>
{% endblock center %}