routes/index.py
from flask import (
    Blueprint,
    render_template,
    session,
    request,
    redirect,
    url_for,
    flash,
    g,
    current_app,
    jsonify,
    make_response
)
from models.users import User
from models.web_view import Web_View
from models.types import Types
from tools.utils import current_user_id, is_login
from tools.log import logger
from tools.pagination import Pagination
from models.weekly import Weekly
import os
import random, string


main = Blueprint('index', __name__)


@main.route('/', methods=['GET', 'POST'])
@is_login
def index():
    Web_View.incre_views()
    page = request.args.get('page', '1', type=int)
    note = Weekly.get_all_obj_by_page(page=page)

    total_num = len(Weekly.get_obj_by_filter())

    total_page = Pagination.get_total_page_num(total_num)

    # 构造文章的分页对象
    pagination = Pagination(int(page), total_page)
    return render_template('index/index.html', note=note, pagination=pagination, endpoint='index.index')


# 根据文章分类，显示文章
@main.route('/note_type/<int:id>')
def note_type(id):
    Web_View.incre_views()
    page = request.args.get('page', '1')
    # 指定分类的所有文章
    note = Weekly.get_all_obj_by_page(page=page, type_id=id)
    # 返回分页对象
    total_num = len(Weekly.get_obj_by_filter(type_id=id))
    total_page = Pagination.get_total_page_num(total_num)
    pagination = Pagination(int(page), total_page)
    return render_template('index/index.html', note=note, pagination=pagination, endpoint='index.note_type', id=id)


@main.route('/person_info', methods=['GET', 'POST'])
@is_login
def person_info():
    if request.method == 'GET':
        u = User.find_by_id(current_user_id())
        return render_template('index/person_info.html', user=u)
    else:
        file = request.files['file']
        file_name = file.filename
        print('file_name, ', file_name)
        ext = file_name.rsplit('.', 1)[1]  # 获取文件后缀
        file_dir = current_app.config['AVATER_IMG_PATH']
        if not os.path.exists(file_dir):
            os.makedirs(file_dir)
        # 将文件名用随机字符串代替
        salt = ''.join(random.sample(string.ascii_letters + string.digits, 12))
        save_name = salt + '.' + ext
        file.save(os.path.join(file_dir,str(save_name)))
        flash('上传头像成功', 'success')

        # 将头像信息写入User表
        user_id = current_user_id()
        User.update_avater(user_id, save_name)
    return redirect(url_for('index.index'))


@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        u = User.validate(request.form)
        if u is None:
            flash('找不到用户或密码错误', 'danger')
        else:
            session['user_id'] = u.id
            session['user_name'] = u.user_name
            logger.info('{} success login'.format(u.user_name))
            flash('登陆成功', 'success')
            return redirect(url_for('index.index'))  # 登录成功
    return render_template('index/login.html')


@main.route('/logout', methods=['GET'])
@is_login
def logout():
    if session['user_id'] and session['user_id'] is not None:
        logger.info('{} success logout'.format(session['user_name']))
        return redirect(url_for('index.login'))
    else:
        return flash('还未登录')


@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        form = request.form
        u = User(form)
        # 验证用户是否合法
        if u.check_username_occupy():
            User.new(u)
            logger.info('{} success register'.format(u.user_name))
            flash('注册成功', 'success')
            return redirect(url_for('index.login'))
        else:
            flash('用户名被占用，请重新输入', 'warning')
    return render_template('index/register.html')


@main.route('/testhttp', methods=['GET', 'POST'])
def testhttp():
    if request.method == 'GET':
        result = make_response(render_template('test_http.html'))
        result.headers['flask-header'] = "wfp"
        return result
    else:
        header = request.headers.get("js-header")
        logger.info('header is {}'.format(header))
        data = jsonify({'result':'ok', 'header': header})
        return data
    return '<h1>none</h1>'

routes/weekly.py
from flask import (
    Blueprint,
    render_template,
    session,
    request,
    redirect,
    url_for,
    g,
    jsonify,
    flash,
    make_response,
    current_app,
)
from models.weekly import Weekly
from models.users import User
from models.conmments import Comments
from models.web_view import Web_View
from models.types import Types
from models.menus import Menus
from tools.utils import current_user_id, is_login
from tools.log import logger
import os, datetime


main = Blueprint('weekly', __name__)


@main.route('/new', methods=['GET'])
@is_login
def new():
    # 返回话题列表
    logger.info('新建文件')
    # TODO；需要优化
    topic = g.my_session.query(Types).all()
    return render_template('weekly/new.html', board=topic)


@main.route('/add', methods=['POST'])
@is_login
def add():
    form = request.form
    user_id = current_user_id()
    note = Weekly(form, user_id=user_id)
    Weekly.new(note)
    flash('发表文章成功', 'success')
    logger.info('add new note id<{}> title<{}>'.format(note.id, note.title))
    return redirect(url_for('index.index'))


@main.route('/detail/<id>/')
def detail(id):
    Web_View.incre_views()
    note = Weekly.find_by_id(id)
    if note is not None:
        note.incre_views()
    else:
        logger.error('get_obj_by_id is None')
  
    # 根据用户Id，查找作者
    author = User.find_by_id(note.user_id).user_name
    
    # 根据文章id，查找其所有评论
    comments = Comments.get_obj_by_filter(note_id=id)
    return render_template('weekly/detail.html', note=note, comments=comments, author=author)


@main.route('/delete/<id>')
@is_login
def delete(id):
    note = Weekly.find_by_id(id)
    title = note.title
    logger.info('note {} delete success'.format(title))
    Weekly.delete(note)
    return redirect(url_for('index.index'))
    

@main.route('/edit/<id>', methods=['GET', 'POST'])
@is_login
def edit(id):
    old_note = Weekly.find_by_id(id)
    content = request.form.get('content', '')
    # 如果为空字符串，表示还没有提交更改
    if content is '':
        topic = Types.get_obj_by_filter()
        author = User.find_by_id(old_note.user_id).user_name
        comments = Comments.get_obj_by_filter(note_id=id)
        return render_template('weekly/edit.html', note=old_note, comments=comments, author=author, board=topic)
    else:
        # 更新数据库
        new_note = Weekly(request.form, old_note.user_id)
        Weekly.update(old_note, new_note)
        return redirect(url_for('weekly.detail', id=id))


@main.route('/detail/add_commit/<id>', methods=['POST'])
@is_login
def add_comment(id):
    content = request.form.get('content', 'null')
    
    # 文章的评论数加1
    note = Weekly.find_by_id(id)
    if note is not None:
        note.incre_replys()
    
    obj = Comments(content, current_user_id(), id)
    Comments.new(obj)
    logger.info('note<{}> add comment '.format(id))
    return redirect(url_for('weekly.detail', id=id))


# 接收editormd中ajax发送的图片，保存到本地，并返回链接
@main.route('/img', methods=['POST'])
def upload_img():
    print('img here')
    file = request.files.get('editormd-image-file')
    if not file:
        res = {
            'success': 0,
            'message': u'图片为空或格式错误'
        }
        return jsonify(res)
    else:
        ex = os.path.splitext(file.filename)[1]
        filename = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file.save(os.path.join(current_app.config['IMG_PATH'], filename))
        logger.info('save img {}'.format(filename))
        res = {
            'success' : 1,
            'message' : u'success',
            'url' : url_for('weekly.get_img', filename=filename)
        }
        return jsonify(res)


# 返回图片
@main.route('/image/<filename>', methods=['GET', 'POST'])
def get_img(filename):
    with open(os.path.join(current_app.config['IMG_PATH'], filename), 'rb') as file:
        r = make_response(file.read())
        return r
        

templates/_acticle_info.html
<div class="topic-cell">
    <a class="user-avater" href="#">
    {% set avater_path = g.my_session.query(User.avater_hash).filter(User.id == n.user_id).first()[0] %}
    <img class="title-avater"  height="40px" width="40px"
     src="{{ url_for('static', filename='img/avater/' ~ avater_path) }}">
    </a>
    <div class="topic-content">
        <h4><a href="{{ url_for('weekly.detail', id=n.id) }}">{{ n.title }}</a></h4>
        <p>
            {{ g.my_session.query(Types.title).filter(Types.id == n.type_id).first()[0] }} • {{ g.my_session.query(User.user_name).filter(User.id == n.user_id).first()[0] }}
            • {{ n.replys }} 个回复 • {{ n.views }} 次浏览 • {{ n.ct }}
        </p>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}bootstrap{% endblock title %}
    </title>
    {% block stylesheet %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/my_web.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/money_free.css') }}">
    {% endblock stylesheet %}
</head>
<body>
<header>
    <div class="header-top">
        <div class="container">
            <h3 class="web-title"><a href="{{ url_for('index.index') }}">{{ g.my_session.query(Web_View).first().title }}</a></h3>
            <p class="web-signature">
                越努力，越幸福
            </p>
        </div>
    </div>
    <!--头部导航栏-->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('index.index') }}"><span class="glyghicon glyghicon-home">首页</span></a></li>
                    {% for menu in g.my_session.query(Menus).all() %}
                    <li class="dropdown">
                        <!--板块文章-->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ menu.title }}<b
                        class="caret"></b></a>
                        <ul class="dropdown-menu">
                            {% for b in g.my_session.query(Types).filter(Types.menu_id == menu.id).all() %}
                               <li>
                                   <a href="{{ url_for(b.url, id=b.id) }} ">{{ b.title }}</a>
                               </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
				</ul>
                <ul class="nav navbar-nav navbar-right">
                    <!--这里应该增加判断是否登录-->
                    <!--用户管理-->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">博客管理<b
                        class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('weekly.new') }}">发表博客</a></li>
                            <li><a href="#">我的博文</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">当前用户<b
                        class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('index.person_info') }}">个人中心</a></li>
                            <li><a href="{{ url_for('index.login') }}">登录</a></li>
                            <li><a href="{{ url_for('index.register') }}">注册</a></li>
                            <li><a href="{{ url_for('index.logout') }}">退出</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

{% block content %}
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 center">
                    <!--提示框-->
                    {% for category, message in get_flashed_messages(with_categories=true) %}
                        <div class="alert alert-{{ category }} alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            {{ message }}
                        </div>
                    {% endfor %}

                    {% block center %}
                    <!--填充中央界面-->
                    {% endblock center %}
                </div>
                <div class="col-lg-4 right">
                    <!--侧边栏-->
                    {% block right %}
                        <div class="entry-box">
                            <h5>
        <strong>
            网站统计
        </strong>
    </h5>
                            <p>
                                "访问量: "
                                <span class="badge">
                                    {{ g.my_session.query(Web_View).first().views }}
                                </span>
                            </p>
                            <p>
                            "文章总数: "
                            <span class="badge">
                                {{ g.my_session.query(Weekly).count() }}
                            </span>
                            "评论总数: "
                            <span class="badge">
                                {{ g.my_session.query(Comments).count() }}
                            </span>
                        </p>
                        </div>
                    {% endblock right %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

<div class="footer">
    <p class="footer-content">
        @2018
        <a href="#">王飞平的网站</a>
        -为自由
    </p>
</div>

<div class="btn-group-vertical floatButton">
    <button id="goTop" class="btn btn-default" title="去顶部" type="button">
        <span class="glyphicon glyphicon-arrow-up"></span>
    </button>
    <button id="refresh" class="btn btn-default" title="刷新" type="button">
        <span class="glyphicon glyphicon-refresh"></span>
    </button>
    <button id="goBottom" class="btn btn-default" title="去底部" type="button">
        <span class="glyphicon glyphicon-arrow-down"></span>
    </button>
</div>

{% block script %}
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/float_button.js') }} "></script>
    <script src="{{ url_for('static', filename='js/moneyfree.js') }} "></script>
{% endblock script %}

</body>
</html>

templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新建周报</title>
    <!-- 暂时不继承模板，因为模板是bootstrap3.0，而这个是2.0的，有空再改 -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            <option value="">请选择</option>
                {% for b in board %}
                <option value="{{ b['Board.board_id'] }}">{{ b['Board.title'] }}</option>
                {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/pagination_macro.html
<!-- 分页宏， 直接在模板中引用即可 -->
{% macro pagination(pagination, endpoint, fragment='') %}

<ul class="pagination">
    <li{% if not pagination.have_prev %} class="disabled" {% endif %}>
        <a href="{{ url_for(endpoint, page=pagination.page - 1, **kwargs) }}{{ fragment }}">&laquo;</a>
    </li>
    {% for p in range(pagination.total_page)  %}
        <li><a href="{{ url_for(endpoint, page=p + 1, **kwargs) }}{{ fragment }}">{{ p + 1 }}</a></li>
    {% endfor %}
    <li{% if not pagination.have_next %} class="disabled" {% endif %}>
        <a href="{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}{{ fragment }}">&raquo;</a>
    </li>
</ul>
{% endmacro %}

templates/test_http.html
{% extends 'base.html' %}
{% import "pagination_macro.html" as macros %}
{% block title %} 测试http协议扩展 {% endblock %}

{% block center %}
    <div class="entry-box">
        <div id="display" class="alert alert-success alert-dismissable" hidden="hidden">
            <span class="display_header">
            </span>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        </div>
        <input type="text" id="header" placeholder="input request header">
        <button type="submit" id="button">提交请求</button>
    </div>
{% endblock center %}

{% block script %}
    {{ super() }}
<script>

    $(document).ready(function(){
        $("#button").click(function(){
            var user_header = $("#header").val();

            var data = {};
            data.test_header = user_header;
            console.log('input  ' + data.test_header);

            $.ajax({
                url: '{{ url_for('index.testhttp') }}',
                type: 'POST',
                data : data,
                dataType: 'json',
                success : function(data){
                    $(".display_header").empty();
                    console.log("data['header'] is " + data['header']);
                    console.log("data['result'] is " + data['result']);
                    $(".display_header").append("自定义 request header : " + data['header']);
                    $(".alert").show();
                },
                error : function(data){
                    alert('error');
                },
                beforeSend: function(request){
                    request.setRequestHeader("js-header", user_header);
                }
            });
        });
    });
</script>
{% endblock %}